name: MentorPath CD Pipeline

on:
    # Déclenchement manuel (pour tester)
  workflow_dispatch:

  workflow_run:
    workflows: ["MentorPath CI Pipeline"]
    types:
      - completed
    branches: [develop]

env:
  DOCKERHUB_USERNAME: elansarioumaima

jobs:
  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-22.04
    
 
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/mentorpath || mkdir -p /home/ubuntu/mentorpath
            cd /home/ubuntu/mentorpath
            
            # Create .env from secrets
            cat > .env << 'EOF'
            POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            EOF
            
            # Login to Docker Hub
            echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ env.DOCKERHUB_USERNAME }} --password-stdin
            
            # Pull and deploy
            docker compose pull
            docker compose up -d
            
            # Show status
            docker ps